---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-deployer
  namespace: staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-deployer
  namespace: production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-deployer-role
  namespace: staging
rules:
  - apiGroups: ["", "apps", "extensions", "networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-deployer-role
  namespace: production
rules:
  - apiGroups: ["", "apps", "extensions", "networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-deployer-binding
  namespace: staging
subjects:
  - kind: ServiceAccount
    name: gitlab-deployer
    namespace: staging
roleRef:
  kind: Role
  name: gitlab-deployer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-deployer-binding
  namespace: production
subjects:
  - kind: ServiceAccount
    name: gitlab-deployer
    namespace: production
roleRef:
  kind: Role
  name: gitlab-deployer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-deployer-token
  namespace: staging
  annotations:
    kubernetes.io/service-account.name: gitlab-deployer
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-deployer-token
  namespace: production
  annotations:
    kubernetes.io/service-account.name: gitlab-deployer
type: kubernetes.io/service-account-token
